id: drupal-nodes-with-misconfigured-access-controls
info:
  author: Generated
  description: Drupal Nodes can contain sensitive data and if permissions are not
    enforced, they can leak private data to unauthorized users.
  name: Drupal Nodes with Misconfigured Access Controls
  reference:
  - https://bugology.intigriti.io/misconfig-mapper-docs/services/drupal/drupal-nodes-with-misconfigured-access-controls
  - https://twitter.com/adrien_jeanneau/status/1273952564430725123
  - https://www.drupal.org/docs/core-modules-and-themes/core-modules/node-module/about-nodes
  - https://web.archive.org/web/20220203132234/https://0xblackbird.github.io/blog/post1
  severity: medium
  tags: misconfig-mapper-template,drupal
requests:
- matchers:
  - status:
    - 200
    type: status
  - type: word
    words:
    - <meta name="generator" content="Drupal
    - (https://www.drupal.org)
    - /sites/default/files/css/
  - type: word
    words:
    - <meta name="generator" content="Drupal
  method: GET
  path:
  - https://{TARGET}/node/1
